import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8FAFC" },
  scrollContent: { padding: 20 },
  header: { marginBottom: 25 },
  title: { fontSize: 28, fontWeight: "bold", color: "#1E293B" },
  subtitle: { fontSize: 16, color: "#64748B", marginTop: 5 },
  scoreCard: {
    backgroundColor: "#22C55E",
    borderRadius: 20,
    padding: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 25,
    elevation: 4,
  },
  scoreLabel: { color: "#DCFCE7", fontSize: 16 },
  scoreValue: { color: "#FFF", fontSize: 32, fontWeight: "bold" },
  progressSection: { marginBottom: 30 },
  progressTextRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  progressLabel: { fontWeight: "600", color: "#475569" },
  progressPercent: { fontWeight: "bold", color: "#22C55E" },
  progressBarBg: { height: 10, backgroundColor: "#E2E8F0", borderRadius: 5 },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#22C55E",
    borderRadius: 5,
  },
  listContainer: { gap: 15 },
  taskItem: {
    backgroundColor: "#FFF",
    padding: 18,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#F1F5F9",
  },
  taskItemCompleted: { borderColor: "#22C55E", backgroundColor: "#F0FDF4" },
  taskInfo: { flexDirection: "row", alignItems: "center", flex: 1 },
  taskText: {
    marginLeft: 12,
    fontSize: 16,
    color: "#334155",
    fontWeight: "500",
  },
  taskTextCompleted: { color: "#166534", textDecorationLine: "line-through" },
  pointBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FEF9C3",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  pointText: {
    marginLeft: 4,
    fontSize: 12,
    fontWeight: "bold",
    color: "#854D0E",
  },
});
